### ISSUE TITLE
The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined

### ISSUE THREAD

**Issue by TheRealKizu** [TheRealKizu/Alaia#15]
```
TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Hmac.update (internal/crypto/hash.js:84:11)
    at Object.hmacSha256 (/home/kizu/Alaia/dist/lib/utils/Utils.js:73:31)
    at Object.<anonymous> (/home/kizu/Alaia/dist/server.js:22:35)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/kizu/Alaia/dist/index.js:6:1)
```

**Comment by Intevel** [comment]
Do you have a solution for this problem? I had the same :(
